### ISSUE TITLE
Missing files.

### ISSUE THREAD

**Issue by ManuFerHi** [ZXMicroJack/amstrad-cpc#2]
Hello, I am trying to synthesize the version for ZX spectrum Next, but it always gives me an error when doing make in the firmware folder.
make: /opt/zpu/bin/zpu-elf-as : Command not found
I tried to install the retrogambling toolchain but I can't compile.
Could you put a .rar with the contents of /firmware already compiled? you would do me a big favor.

**Comment by ManuFerHi** [comment]
I already managed to compile the code, I close the issue.

**Comment by ZXMicroJack** [comment]
My apologies, only just spotted this.  I'm happy you got sorted, and even
happier this is coming across to the Next.

Cheers,
MJ

**Comment by ZXMicroJack** [comment]
Not sure if it was clear from the Readme, I think not looking at it...  but the ctrl module should be taken from this repo....

https://github.com/ZXMicroJack/ctrl-module/tree/amstradcpc

**Comment by ManuFerHi** [comment]
Yes, I saw that it was the Branch Amstrad Tag4, since the main one did not work, but what cost me the most is to install the Toolchain to compile that I am a Windows user. But I got it in virtual console.

**Comment by ZXMicroJack** [comment]
Yes, sorry, I'm an eternal linux user - sometimes I forget anything else
exists.  Other than this toolchain which was quite contained on Linux, I
generally put more complex ones that involve installing SDKs as docker
containers - they spin up quick and build resulting in files on your disk
without the need to export them from a virtual machine.  Also running the
docker container to build is as easy, invoking a single command from your
cmd line to build it.

**Comment by ZXMicroJack** [comment]
https://github.com/shamrin/zpugcc-docker - someone beat me to it.
